### PR TITLE
Use shields.io badge for npm-version

### PR DESCRIPTION
**Pull request by SimenB**
For consistency.
Also, the current image is just weird :laughing:

### CODE REVIEW

**Comment by vvo** [comment]
@SimenB I chose the current badge because it's SHINY :)

**Comment by SimenB** [comment]
Not sure how this constitutes shiny, but sure :laughing: 

image

Btw, any idea when the full (aka no-beta) version of this lib is out? I used it to replace Sinon at work (and it works great thanks!), but having the word beta made me go for version 3 instead. I prefer the event driven nature of version 4 :smile:

**Comment by vvo** [comment]
I guess we can release now and fix two bugs, it had beta for too long while it works really great now: event driven + nodejs support. still some planned work but it works.

It will also fixes the version badge :). I use only this version badge, really about preferences, no big deal.

**Comment by vvo** [comment]
done

**Comment by vvo** [comment]
2015-05-24-225057_734x102_scrot

**Comment by vvo** [comment]
compared to 
2015-05-24-225133_766x110_scrot

**Comment by SimenB** [comment]
@vvo Awesome, thanks.

**Comment by vvo** [comment]
@SimenB where do you use it?

**Comment by SimenB** [comment]
At work. Closed source project, so I can't show it. :cry:

We had huge problems making sinon work with webpack, and with sinon spending aaaages releasing version 2 with proper CJS support, I found this alternative. Combined with Lolex, I was able to drop the sinon dep. As we use Jasmine, we already had spies and assertions anyway, much cleaner having network-mocking in its own module :smile:

**Comment by SimenB** [comment]
@vvo regarding the badge, I didn't notice the `sup` wrapping... I "fixed" it as I got curious :laughing: 

image

**Comment by SimenB** [comment]
@vvo http://vb.teelaun.ch/ seems to be dead, might want to merge this :smile:

**Comment by SimenB** [comment]
@vvo 
image

**Comment by vvo** [comment]
Can you resubmit? :)

**Comment by SimenB** [comment]
Just repone this one

**Comment by SimenB** [comment]
oh never mind, I seem to have deleted the branch

**Comment by SimenB** [comment]
se #17

**Pull request closed without merging**
